### ISSUE TITLE
Server Code Debug 

### ISSUE THREAD

**Issue by taquiles** [skolmer/react-hot-boilerplate-vscode#10]
Hi skolmer, 

As I didn't figure out why I could not debug (set breakpoints and so on) on server side code with your setup (maybe I've missed something, no?!), I've updated launch.json adding the following so server side code may be debuged:

{
      {
	"version": "0.2.0",
	"configurations": 
        [
            {
                "name": "Server",
                "type": "node",
                "request": "launch",
                "program": "${workspaceRoot}/devServer.js",
                "cwd": "${workspaceRoot}"
            },
            {
                "name": "Client",
                "type": "chrome",
                "request": "launch",
                "webRoot": "${workspaceRoot}",
                "url": "http://localhost:3000", 
                "userDataDir": "${workspaceRoot}/.vscode/chrome",
                "sourceMaps": true,
                "preLaunchTask": "development",
                "smartStep": true,
                "internalConsoleOptions": "openOnSessionStart",
                "skipFiles": [
                    "node_modules/**"
                ],
                "sourceMapPathOverrides": {
                    "webpack:///*": "${webRoot}/*"
                }
            }
        ],
            "compounds": [
            {
                "name": "Server/Client Debug",
                "configurations": ["Server", "Client"]
            }]
}

**Comment by skolmer** [comment]
Hi, I haven't tried the new multi target debugging feature of vscode yet. But reading the [documentation](https://code.visualstudio.com/docs/editor/debugging#_multitarget-debugging) I would expect this to work. 

Sorry I cannot help here but please keep me updated if you find a solution to your problem.

**Comment by taquiles** [comment]
Hi Skolmer, 
I was not asking you for help ;-), but instead giving you some help so your boilerplate would allow for server side code debug as I've have already tested it. :-).

**Comment by skolmer** [comment]
Thank you and sorry for the misunderstanding. Great to see this setup is working. Do you want to send a pull request? I would be happy to merge it in.

**Comment by GGAlanSmithee** [comment]
see #11

**Comment by skolmer** [comment]
https://github.com/skolmer/react-hot-boilerplate-vscode/pull/11#issuecomment-365716035
