### ISSUE TITLE
Cannot set breakpoint

### ISSUE THREAD

**Issue by douglasjwoods** [skolmer/react-hot-boilerplate-vscode#6]
I have downloaded and installed as per instructions. The app works correctly, and hot loading is working as well, but when I try to set a breakpoint on the tick() in Counter.js it gives a error "Breakpoint ignored because generated code not found (source map problem)?)"

I am using vscode 1.7.2  and latest version of the recommended extensions
Debugger for chrome 2.3.2
ESLint 1.1.0
npm 3.3.0
npm intellisense 0.1.4
Reactjs code snippets 1.2.0

Rgds
Douglas

**Comment by douglasjwoods** [comment]
I just tried reverting the webpack.config.dev.js to use 

> devtool: '#cheap-eval-source-map',

and debugging is now working :-)

Rgds
Douglas

**Comment by douglasjwoods** [comment]
I also tried starting the chrome devtools (ctrl shift I) and the chrome browser terminated.  (I was wanting to use the React chrome extension)
Rgds
Douglas

**Comment by skolmer** [comment]
Hi Douglas,

thanks for your feedback.
I will check the sourcemap configuration again when I find some time. There were some issues with '#cheap-eval-source-map' in earlier versions of vscode chrome debugger that might be resolved in the latest version of chrome and/or chrome debugger.

The second issue is a limitation in the chrome debugging protocol. Chrome only allows one debugger to be attached at a time. Therefore when you open the devtools it will detach the vscode chrome debugger and the vscode chrome debugger will close your chrome instance.

**Comment by skolmer** [comment]
@douglasjwoods I have changed the source-map config again to use #cheap-module-eval-source-map. This seems to work in chrome devtools and with vscode-chrome-debug
https://github.com/skolmer/react-hot-boilerplate-vscode/commit/671807f79b702d5e3018112b0b0f563f3013aa57
