### ISSUE TITLE
[eslint] Unable to resolve path to module 'react-router'. (import/no-unresolved)

### ISSUE THREAD

**Issue by jankidepala** [skolmer/react-hot-boilerplate-vscode#7]
I am having issues running debugger in VSCode. This one is running bt wwhen I try to import new package gives this error : [eslint] Unable to resolve path to module 'react-router'. (import/no-unresolved)
Any suggestion??

**Comment by skolmer** [comment]
Hi @jankidepala normally this error only occurs if the imported library is missing in `node_modules` directory. Have you double checked that `react-router` has been installed correctly? You can find more details about this eslint rule here: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unresolved.md
