### ISSUE TITLE
Error in development task output

### ISSUE THREAD

**Issue by afhole** [skolmer/react-hot-boilerplate-vscode#8]
When starting the development task for web pack dev server I receive the following error:

`The problem pattern is invalid. It must have at least a file, message and line or location match group.`

It doesn't seem to be critical, dev server does start, but I presume this may interfere with parsing errors from dev server?

**Comment by skolmer** [comment]
Hi, you are right this not a critical issue. It is related to a limitation in the problemMatcher configuration in tasks.json. Please take a look at the following discussion: https://github.com/Microsoft/vscode/issues/6209#issuecomment-218175415

**Comment by skolmer** [comment]
Feel free to reopen this issue if you have more questions.

**Comment by skolmer** [comment]
There was a change in the latest insider builds that caused the problem matcher to stop working as expected. This needs to be fixed. https://github.com/Microsoft/vscode/issues/6209#issuecomment-287427213
